import { Linking, ScrollView, StyleSheet, Text, View } from "react-native";
import Constants from "expo-constants";
import { API_BASE_URL } from "@/lib/config";
import { detectLanguage } from "@/lib/language";
import { colors, radius, spacing } from "@/lib/theme";
import { ExplainLanguage } from "@/lib/types";

const L: Record<
  ExplainLanguage,
  { privacy: string; privacyBody: string; privacyLink: string; about: string; aboutBody: string; version: string; support: string; footer: string }
> = {
  pt: {
    privacy: "Privacidade",
    privacyBody: "Suas fotos são analisadas apenas para gerar a explicação e não ficam guardadas em nenhum servidor. Seu histórico fica salvo só neste aparelho.",
    privacyLink: "Ler a política de privacidade completa →",
    about: "Sobre",
    aboutBody: "Explicare não é um dispositivo médico e não diagnostica, trata, cura ou previne nenhuma condição médica. As explicações são geradas por inteligência artificial e são um resumo educativo em linguagem simples — não substituem a orientação de um médico ou farmacêutico.",
    version: "Versão",
    support: "Suporte",
    footer: "Um produto Cortex Tech",
  },
  en: {
    privacy: "Privacy",
    privacyBody: "Your photos are analyzed only to generate the explanation and are never stored on any server. Your history is saved only on this device.",
    privacyLink: "Read the full privacy policy →",
    about: "About",
    aboutBody: "Explicare is not a medical device and does not diagnose, treat, cure, or prevent any medical condition. Explanations are generated by artificial intelligence and are an educational, plain-language summary — they do not replace guidance from a doctor or pharmacist.",
    version: "Version",
    support: "Support",
    footer: "A Cortex Tech product",
  },
  es: {
    privacy: "Privacidad",
    privacyBody: "Sus fotos se analizan solo para generar la explicación y nunca se guardan en ningún servidor. Su historial se guarda solo en este dispositivo.",
    privacyLink: "Leer la política de privacidad completa →",
    about: "Acerca de",
    aboutBody: "Explicare no es un dispositivo médico y no diagnostica, trata, cura ni previene ninguna afección médica. Las explicaciones son generadas por inteligencia artificial y son un resumen educativo en lenguaje simple — no reemplazan la orientación de un médico o farmacéutico.",
    version: "Versión",
    support: "Soporte",
    footer: "Un producto de Cortex Tech",
  },
  fr: {
    privacy: "Confidentialité",
    privacyBody: "Vos photos sont analysées uniquement pour générer l'explication et ne sont jamais conservées sur un serveur. Votre historique est enregistré uniquement sur cet appareil.",
    privacyLink: "Lire la politique de confidentialité complète →",
    about: "À propos",
    aboutBody: "Explicare n'est pas un dispositif médical et ne diagnostique, ne traite, ne guérit ni ne prévient aucune condition médicale. Les explications sont générées par intelligence artificielle et constituent un résumé éducatif en langage simple — elles ne remplacent pas l'avis d'un médecin ou d'un pharmacien.",
    version: "Version",
    support: "Assistance",
    footer: "Un produit Cortex Tech",
  },
  zh: {
    privacy: "隐私",
    privacyBody: "您的照片仅用于生成解释，绝不会保存在任何服务器上。您的历史记录仅保存在本设备中。",
    privacyLink: "阅读完整隐私政策 →",
    about: "关于",
    aboutBody: "Explicare 不是医疗器械，不能诊断、治疗、治愈或预防任何疾病。这些解释由人工智能生成，是简单易懂的教育性摘要——不能替代医生或药剂师的指导。",
    version: "版本",
    support: "支持",
    footer: "Cortex Tech 出品",
  },
};

export default function SettingsScreen() {
  const t = L[detectLanguage()];
  return (
    <ScrollView contentContainerStyle={styles.container}>
      <View style={styles.card}>
        <Text style={styles.sectionTitle}>{t.privacy}</Text>
        <Text style={styles.bodyText}>{t.privacyBody}</Text>
        <Text style={styles.link} onPress={() => Linking.openURL(`${API_BASE_URL}/privacy`)}>
          {t.privacyLink}
        </Text>
      </View>

      <View style={styles.card}>
        <Text style={styles.sectionTitle}>{t.about}</Text>
        <Text style={styles.bodyText}>{t.aboutBody}</Text>
        <Text style={styles.bodyText}>{t.version} {Constants.expoConfig?.version ?? "1.0.0"}</Text>
      </View>

      <View style={styles.card}>
        <Text style={styles.sectionTitle}>{t.support}</Text>
        <Text style={styles.link} onPress={() => Linking.openURL("mailto:cortextechbr@gmail.com")}>
          cortextechbr@gmail.com
        </Text>
      </View>

      <Text style={styles.footer}>{t.footer}</Text>
    </ScrollView>
  );
}

const styles = StyleSheet.create({
  container: { padding: spacing.lg, gap: spacing.md, backgroundColor: colors.bg, flexGrow: 1 },
  card: {
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderWidth: 1,
    borderRadius: radius.lg,
    padding: spacing.lg,
    gap: spacing.xs,
  },
  sectionTitle: { fontSize: 14, fontWeight: "800", color: colors.primaryDark, textTransform: "uppercase" },
  bodyText: { fontSize: 14, color: colors.text, lineHeight: 20 },
  link: { fontSize: 14, color: colors.primary, fontWeight: "700", marginTop: spacing.xs },
  footer: { textAlign: "center", color: colors.textMuted, fontSize: 12, marginTop: spacing.lg },
});
