import { useState } from "react";
import { Pressable, StyleSheet, Text, View } from "react-native";
import * as Speech from "expo-speech";
import { CalmPanel } from "./CalmPanel";
import { colors, radius, spacing } from "@/lib/theme";
import { ExplainLanguage, LabExplanation, LabParameter, LabParameterStatus } from "@/lib/types";

interface Copy {
  demo: string;
  summary: string;
  readAloud: string;
  stop: string;
  normal: string;
  attention: string;
  outOfRange: string;
  undetermined: string;
  questions: string;
  aiGenerated: string;
  disclaimer: string;
}

const L: Record<ExplainLanguage, Copy> = {
  pt: {
    demo: "Modo demonstração — configure a chave de IA no servidor pra respostas reais.",
    summary: "Resumo",
    readAloud: "Ouvir",
    stop: "Parar",
    normal: "normal",
    attention: "atenção",
    outOfRange: "fora da faixa",
    undetermined: "indeterminado",
    questions: "Perguntas pro médico",
    aiGenerated: "✨ Explicação gerada por inteligência artificial",
    disclaimer:
      "Explicare não é um dispositivo médico e não diagnostica, trata, cura ou previne nenhuma condição médica. Sempre confirme com um médico antes de tomar qualquer decisão com base nesses resultados.",
  },
  en: {
    demo: "Demo mode — configure the AI key on the server for real answers.",
    summary: "Summary",
    readAloud: "Read aloud",
    stop: "Stop",
    normal: "normal",
    attention: "attention",
    outOfRange: "out of range",
    undetermined: "undetermined",
    questions: "Questions for your doctor",
    aiGenerated: "✨ Explanation generated by artificial intelligence",
    disclaimer:
      "Explicare is not a medical device and does not diagnose, treat, cure, or prevent any medical condition. Always confirm with a licensed doctor before making any decision based on these results.",
  },
  es: {
    demo: "Modo demostración — configure la clave de IA en el servidor para respuestas reales.",
    summary: "Resumen",
    readAloud: "Escuchar",
    stop: "Detener",
    normal: "normal",
    attention: "atención",
    outOfRange: "fuera de rango",
    undetermined: "indeterminado",
    questions: "Preguntas para su médico",
    aiGenerated: "✨ Explicación generada por inteligencia artificial",
    disclaimer:
      "Explicare no es un dispositivo médico y no diagnostica, trata, cura ni previene ninguna afección médica. Confirme siempre con un médico antes de tomar cualquier decisión basada en estos resultados.",
  },
  fr: {
    demo: "Mode démo — configurez la clé d'IA sur le serveur pour de vraies réponses.",
    summary: "Résumé",
    readAloud: "Écouter",
    stop: "Arrêter",
    normal: "normal",
    attention: "à surveiller",
    outOfRange: "hors norme",
    undetermined: "indéterminé",
    questions: "Questions pour votre médecin",
    aiGenerated: "✨ Explication générée par intelligence artificielle",
    disclaimer:
      "Explicare n'est pas un dispositif médical et ne diagnostique, ne traite, ne guérit ni ne prévient aucune condition médicale. Confirmez toujours avec un médecin avant de prendre une décision basée sur ces résultats.",
  },
  zh: {
    demo: "演示模式 — 请在服务器上配置 AI 密钥以获取真实回答。",
    summary: "摘要",
    readAloud: "朗读",
    stop: "停止",
    normal: "正常",
    attention: "需留意",
    outOfRange: "超出范围",
    undetermined: "无法判断",
    questions: "向医生提出的问题",
    aiGenerated: "✨ 本解释由人工智能生成",
    disclaimer: "Explicare 不是医疗器械，不能诊断、治疗、治愈或预防任何疾病。在根据这些结果做出任何决定之前，请务必咨询执业医生。",
  },
};

const SPEECH_LOCALE: Record<ExplainLanguage, string> = {
  pt: "pt-BR",
  en: "en-US",
  es: "es-ES",
  fr: "fr-FR",
  zh: "zh-CN",
};

const STATUS_STYLE: Record<LabParameterStatus, { dot: keyof typeof styles; tag: keyof typeof styles }> = {
  normal: { dot: "dotNormal", tag: "tagNormal" },
  attention: { dot: "dotAttention", tag: "tagAttention" },
  out_of_range: { dot: "dotOutOfRange", tag: "tagOutOfRange" },
  undetermined: { dot: "dotUndetermined", tag: "tagUndetermined" },
};

export function LabResultView({
  explanation,
  language,
  showCheckin,
}: {
  explanation: LabExplanation;
  language: ExplainLanguage;
  /** Whether the calming panel should render (worried check-in OR the AI itself flagged seekCareSoon). */
  showCheckin: boolean;
}) {
  const t = L[language];
  const statusLabel: Record<LabParameterStatus, string> = {
    normal: t.normal,
    attention: t.attention,
    out_of_range: t.outOfRange,
    undetermined: t.undetermined,
  };
  const [isReading, setIsReading] = useState(false);

  function toggleReadAloud() {
    if (isReading) {
      Speech.stop();
      setIsReading(false);
      return;
    }
    const text = [explanation.summary].join(". ");
    Speech.speak(text, {
      language: SPEECH_LOCALE[language],
      onDone: () => setIsReading(false),
      onStopped: () => setIsReading(false),
      onError: () => setIsReading(false),
    });
    setIsReading(true);
  }

  return (
    <View style={{ gap: spacing.md }}>
      {explanation.isDemo && (
        <View style={styles.demoBanner}>
          <Text style={styles.demoText}>{t.demo}</Text>
        </View>
      )}

      <Text style={styles.aiGeneratedTag}>{t.aiGenerated}</Text>

      {showCheckin && (
        <CalmPanel reassurance={explanation.reassurance} seekCareSoon={explanation.seekCareSoon} language={language} />
      )}

      <View style={styles.card}>
        <View style={styles.cardHeader}>
          <Text style={styles.examTitle}>{explanation.examTitle}</Text>
          <Pressable onPress={toggleReadAloud} style={styles.readAloudButton}>
            <Text style={styles.readAloudText}>{isReading ? `⏹ ${t.stop}` : `🔊 ${t.readAloud}`}</Text>
          </Pressable>
        </View>
        <Text style={styles.sectionLabel}>{t.summary}</Text>
        <Text style={styles.bodyText}>{explanation.summary}</Text>
      </View>

      {explanation.parameters.map((p: LabParameter, i: number) => {
        const style = STATUS_STYLE[p.status];
        return (
          <View key={i} style={styles.card}>
            <View style={styles.paramHeader}>
              <Text style={styles.paramName}>{p.name}</Text>
              <View style={[styles.tag, styles[style.tag] as object]}>
                <View style={[styles.dot, styles[style.dot] as object]} />
                <Text style={styles.tagText}>{statusLabel[p.status]}</Text>
              </View>
            </View>
            {(p.valueFound || p.referenceRange) && (
              <Text style={styles.paramValue}>
                {p.valueFound}
                {p.referenceRange ? ` · ${p.referenceRange}` : ""}
              </Text>
            )}
            <Text style={styles.bodyText}>{p.explanation}</Text>
          </View>
        );
      })}

      {explanation.questionsForDoctor.length > 0 && (
        <View style={styles.card}>
          <Text style={styles.sectionLabel}>{t.questions}</Text>
          {explanation.questionsForDoctor.map((q: string, i: number) => (
            <Text key={i} style={styles.bodyText}>
              • {q}
            </Text>
          ))}
        </View>
      )}

      <Text style={styles.disclaimer}>{t.disclaimer}</Text>
      {explanation.disclaimer && explanation.disclaimer !== t.disclaimer && (
        <Text style={styles.disclaimer}>{explanation.disclaimer}</Text>
      )}
    </View>
  );
}

const styles = StyleSheet.create({
  demoBanner: {
    backgroundColor: colors.warningBg,
    borderColor: colors.warningBorder,
    borderWidth: 1,
    borderRadius: radius.md,
    padding: spacing.sm,
  },
  demoText: { color: colors.warning, fontSize: 13 },
  aiGeneratedTag: { fontSize: 12, color: colors.textMuted, fontWeight: "700", textAlign: "center" },
  card: {
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderWidth: 1,
    borderRadius: radius.lg,
    padding: spacing.lg,
    gap: spacing.xs,
  },
  cardHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: spacing.xs },
  examTitle: { fontSize: 19, fontWeight: "800", color: colors.text, flexShrink: 1 },
  readAloudButton: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.pill,
    paddingHorizontal: spacing.sm,
    paddingVertical: 6,
  },
  readAloudText: { fontSize: 12, fontWeight: "700", color: colors.primaryDark },
  sectionLabel: { fontSize: 13, fontWeight: "800", color: colors.primaryDark, textTransform: "uppercase", letterSpacing: 0.4 },
  bodyText: { fontSize: 15, color: colors.text, lineHeight: 21 },
  paramHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "flex-start", gap: spacing.sm },
  paramName: { fontSize: 16, fontWeight: "800", color: colors.text, flex: 1 },
  paramValue: { fontSize: 14, fontWeight: "600", color: colors.textMuted, fontVariant: ["tabular-nums"] },
  tag: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    borderRadius: radius.pill,
    paddingHorizontal: spacing.sm,
    paddingVertical: 3,
  },
  tagText: { fontSize: 11, fontWeight: "800", textTransform: "uppercase", letterSpacing: 0.3 },
  dot: { width: 7, height: 7, borderRadius: 4 },
  tagNormal: { backgroundColor: colors.border },
  dotNormal: { backgroundColor: colors.primary },
  tagAttention: { backgroundColor: colors.warningBg },
  dotAttention: { backgroundColor: colors.warning },
  tagOutOfRange: { backgroundColor: colors.dangerBg },
  dotOutOfRange: { backgroundColor: colors.danger },
  tagUndetermined: { backgroundColor: "#F1F5F9" },
  dotUndetermined: { backgroundColor: colors.textMuted },
  disclaimer: { fontSize: 12, color: colors.textMuted, fontStyle: "italic", textAlign: "center", paddingHorizontal: spacing.md },
});
